# Use a specific Node.js version
FROM node:9.9.0

# Create and define the node application directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

EXPOSE 8081
CMD ["node", "index.js"]
