version: '3.8'
services:
  spring-boot-app:
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: demouser
      SPRING_DATASOURCE_PASSWORD: DemoPa$$

  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: DemoPa$$
      POSTGRES_DB: db
    ports:
      - "5432:5432"
