version: '3.8'
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile-springboot
    ports:
      - "8080:8080"
    depends_on:
      - db

  node-app:
    build:
      context: .
      dockerfile: Dockerfile-nodeapp
    ports:
      - "8081:8081"

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
