## Stage 1: Build the application
#FROM maven:3.6.3-jdk-8 as build
#COPY pom.xml /home/app/
#COPY src /home/app/src
#WORKDIR /home/app
#RUN mvn clean package
#
## Stage 2: Setup the runtime container
#FROM openjdk:8-jre-slim
#COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","/usr/local/lib/app.jar"]

# Stage 1: Build the application
FROM maven:3.6.3-jdk-8 as builder
WORKDIR /app
COPY pom.xml .
COPY src /app/src
RUN mvn clean package

# Stage 2: Setup the runtime environment
FROM openjdk:8-jre-slim
COPY --from=builder /app/target/*.jar /app/app.jar
EXPOSE 8080
CMD ["java", "-jar", "/app/app.jar"]
